name: Dockerise
run-name: ${{ github.actor }} is building a docker image 🚀
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: Nathan-GASC
      - name: ls
        run: ls .
      - name: build
        run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
      - name: docker-hub login
        run: docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
      - name: docker-hub push
        run: docker push "${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest"