name: Dockerise
run-name: ${{ github.actor }} is building a docker image 🚀
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - runs:
          using: 'docker'
          image: 'Dockerfile'