name: Dockerise
run-name: ${{ github.actor }} is building a docker image 🚀
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: ls
        uses: ls
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false