name: Dockerise
run-name: ${{ github.actor }} is building a docker image 🚀
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: Nathan-GASC
      - name: cd
        run: cd ./Docker
      - name: checkout
        run: git checkout Nathan-GASC
      - name: build
        run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest